name    'xaque208-bacula'
version '0.2.0'
source 'https://github.com/xaque208/puppet-bacula'
author 'xaque208'
license 'Apache License, Version 2.0'
summary 'A bacula module stolen from the Puppet Labs Operations team'
description 'UNKNOWN'
project_page 'https://github.com/xaque208/puppet-bacula'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'puppetlabs/stdlib', '>=4.4.0'
dependency 'ploperations/puppet', '>=0.12.0'
dependency 'puppetlabs/postgresql', '>=4.1.0'
